// Decompiled with JetBrains decompiler
// Type: TheSite.Classi.AnalisiStatistiche.NomiStr
// Assembly: ME, Version=1.0.3728.28568, Culture=neutral, PublicKeyToken=null
// MVID: C29CC0F3-9682-4F13-A7DC-CF27C967E605
// Assembly location: C:\SIR_LAVORO\ME.dll

namespace TheSite.Classi.AnalisiStatistiche
{
  public class NomiStr
  {
    protected string GET_RDL_MESE_RICHIESTA => "PACK_ANALISI_STATISTICHE.GET_RDL_MESE_RICHIESTA";

    protected string GET_RDL_MESE_ASSEGNATA => "PACK_ANALISI_STATISTICHE.GET_RDL_MESE_ASSEGNATA";

    protected string GET_RDL_MESE_COMPLETATA => "PACK_ANALISI_STATISTICHE.GET_RDL_MESE_COMPLETATA";

    protected string GET_RDL_DITTA_RICHIESTA => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_RICHIESTA";

    protected string GET_RDL_DITTA_ASSEGNATA => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_ASSEGNATA";

    protected string GET_RDL_DITTA_COMPLETATA => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_COMPLETATA";

    protected string GET_RDL_STATO_RICHIESTA => "PACK_ANALISI_STATISTICHE.GET_RDL_STATO_RICHIESTA";

    protected string GET_RDL_STATO_ASSEGNATA => "PACK_ANALISI_STATISTICHE.GET_RDL_STATO_ASSEGNATA";

    protected string GET_RDL_STATO_COMPLETATA => "PACK_ANALISI_STATISTICHE.GET_RDL_STATO_COMPLETATA";

    protected string GET_RDL_SERVIZIO_RICHIESTA => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_RICHIESTA";

    protected string GET_RDL_SERVIZIO_ASSEGNATA => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_ASSEGNATA";

    protected string GET_RDL_SERVIZIO_COMPLETATA => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_COMPLETATA";

    protected string GET_RDL_SERVIZIO_MESI_RICH => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_MESI_RICH";

    protected string GET_RDL_SERVIZIO_MESI_ASSEGN => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_MESI_ASSEGN";

    protected string GET_RDL_SERVIZIO_MESI_COMP => "PACK_ANALISI_STATISTICHE.GET_RDL_SERVIZIO_MESI_COMP";

    protected string GET_RDL_DITTA_MESI_RICH => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_MESI_RICH";

    protected string GET_RDL_DITTA_MESI_ASSEGN => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_MESI_ASSEGN";

    protected string GET_RDL_DITTA_MESI_COMP => "PACK_ANALISI_STATISTICHE.GET_RDL_DITTA_MESI_COMP";

    protected string get_giud_ser_tip => "PACK_ANALISI_STATISTICHE.get_giud_ser_tip";

    protected string get_giud_serv_mesi => "PACK_ANALISI_STATISTICHE.get_giud_serv_mesi";

    protected string get_giudizio_servizio => "PACK_ANALISI_STATISTICHE.get_giudizio_servizio";
  }
}
